
spring:
  application:
    name: demo
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
    group:
      local: local, local_db
      deploy_blue: deploy_blue, deploy_db
      deploy_red: deploy_red, deploy_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET}
  expirationMillis: 86400000

---

spring:
  config:
    activate:
      on-profile: local
server:
  serverName: local_server
  port: 8080

---

spring:
  config:
    activate:
      on-profile: deploy_blue
server:
  serverName: deploy_blue_server
  port: 8080

---

spring:
  config:
    activate:
      on-profile: deploy_red
server:
  serverName: deploy_red_server
  port: 8081

---

spring:
  config:
    activate:
      on-profile: local_db
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: deploy_db
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



